### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by IlyaMokin** [Terem/terem.github.io#1]
Thanks for the efforts, quite good in general.
I see only issue with scroll in chat area. The area should be split on 3 parts: header,messages list, input message area. And messages list should have own scroll bar.

![image](https://user-images.githubusercontent.com/5592397/97431087-d81c8280-192a-11eb-80d6-743a100f9abe.png)

**Comment by Terem** [comment]
Chat area scrollbar fixed. 
![skype](https://user-images.githubusercontent.com/1094592/97493783-87327b80-1976-11eb-8db2-e6e72a0fa9c9.PNG)
[https://terem.github.io/](url)

**Comment by ilya4321** [comment]
Looking good now! Thank you for the effort
